/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CourierTEC.capalogica.Gestion;

import CourierTEC.capalogica.estructuraDatos.ColaPrioridad;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joel
 */
public class Principal extends javax.swing.JFrame {
    int NFicha=0;
    int NFicha2=0;
    int CantidadP=0;
    int CantidadNP=0;
    String TotalP="";String TotalNP="";   
    int AtendidosP=0;int AtendidosNP=0;   
    int TotalD=0;int TotalM=0;int TotalE=0;int TotalR=0;
    DefaultTableModel ventanilla1= new DefaultTableModel();
    DefaultTableModel ventanilla2= new DefaultTableModel();
    DefaultTableModel ventanilla3= new DefaultTableModel();
    DefaultTableModel ventanilla4= new DefaultTableModel();
    private static Fichas t;
    ColaPrioridad PrioridadP=new ColaPrioridad(4);
    ColaPrioridad PrioridadNP=new ColaPrioridad(4);
    ColaPrioridad Seguridad=new ColaPrioridad(4);
    ColaPrioridad SeguridadNP=new ColaPrioridad(4);
    int cont1=1, cont2=1, cont3=1, cont4=1;
    int CDP=0;int CMP=0;int CEP=0;int CRP=0;
    int CDNP=0;int CMNP=0;int CENP=0;int CRNP=0;
    
    static Fichas Ficha;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        ventanilla1.addColumn("Ventanilla");
        ventanilla2.addColumn("Ventanilla");
        ventanilla3.addColumn("Ventanilla");
        ventanilla4.addColumn("Ventanilla");
        ventanilla1.addColumn("Estado");
        ventanilla2.addColumn("Estado");
        ventanilla3.addColumn("Estado");
        ventanilla4.addColumn("Estado");
        ventanilla1.addColumn("Ficha");
        ventanilla2.addColumn("Ficha");
        ventanilla3.addColumn("Ficha");
        ventanilla4.addColumn("Ficha");
        ventanilla1.addColumn("Tipo de Usuario");
        ventanilla2.addColumn("Tipo de Usuario");
        ventanilla3.addColumn("Tipo de Usuario");
        ventanilla4.addColumn("Tipo de Usuario");
        jTable1.setModel(ventanilla1);
        jTable2.setModel(ventanilla2);
        jTable3.setModel(ventanilla3);
        jTable4.setModel(ventanilla4);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        FieldE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        FieldS = new javax.swing.JTextField();
        ButtonCantVent = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        FieldENoP = new javax.swing.JTextField();
        FieldSNoP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Atender1 = new javax.swing.JButton();
        Liberar1 = new javax.swing.JButton();
        Atender2 = new javax.swing.JButton();
        Liberar2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 750));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Courier TEC");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 40, 125, 29);

        jLabel2.setText("Quiosco de AutoServicio");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 180, 14);

        jLabel3.setText("Seguridad");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 350, 70, 14);

        jLabel4.setText("Entregas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(990, 60, 70, 14);

        jLabel5.setText("Administración");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1000, 400, 90, 14);

        jButton1.setText("Retirar tiquete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 240, 120, 23);

        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 120, 50, 14);

        jLabel7.setText("Correo:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 150, 50, 14);

        jLabel8.setText("Tipo de Usuario:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 180, 90, 14);

        jLabel9.setText("Tipo de Paquete:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 210, 90, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 120, 100, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 150, 100, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Tipo ", "Discapacitado", "Adulto Mayor", "Mujer Embarazada", "Cliente Regular" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(110, 180, 100, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Tipo", "Perecedero", "No perecedero" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(110, 210, 100, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad de ventanillas"));

        jLabel10.setText("Entregas:");

        FieldE.setToolTipText("");
        FieldE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldEActionPerformed(evt);
            }
        });

        jLabel11.setText("Seguridad:");

        FieldS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldSActionPerformed(evt);
            }
        });

        ButtonCantVent.setText("Crear");
        ButtonCantVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCantVentActionPerformed(evt);
            }
        });

        jLabel12.setText("Perecederos");

        jLabel13.setText("NoPerecederos");

        FieldENoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldENoPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FieldS, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(FieldE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel11)))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FieldENoP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(FieldSNoP, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonCantVent, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldENoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldSNoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCantVent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(230, 90, 310, 210);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ventanilla", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(590, 120, 360, 170);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ventanilla", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(960, 120, 350, 170);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ventanilla", "Estado"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 410, 330, 170);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ventanilla", "Estado"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(380, 410, 330, 170);

        jLabel14.setText("Perecederos");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(800, 90, 70, 20);

        jLabel15.setText("NoPerecederos");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1050, 80, 80, 20);

        Atender1.setText("Atender");
        Atender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atender1ActionPerformed(evt);
            }
        });
        getContentPane().add(Atender1);
        Atender1.setBounds(730, 310, 71, 23);

        Liberar1.setText("Liberar");
        Liberar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Liberar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Liberar1);
        Liberar1.setBounds(870, 310, 80, 23);

        Atender2.setText("Atender");
        Atender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atender2ActionPerformed(evt);
            }
        });
        getContentPane().add(Atender2);
        Atender2.setBounds(1070, 310, 71, 23);

        Liberar2.setText("Liberar");
        Liberar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Liberar2ActionPerformed(evt);
            }
        });
        getContentPane().add(Liberar2);
        Liberar2.setBounds(1185, 310, 90, 23);

        jButton3.setText("Estado de Colas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(840, 420, 130, 23);

        jButton2.setText("Estadisticas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(840, 480, 130, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String TipoUsuario="",TipoPaquete="";
        if (jComboBox1.getSelectedIndex()==0 ||jComboBox2.getSelectedIndex()==0 ){
            JOptionPane.showMessageDialog(null,"Debe seleccionar un tipo de Usuario y Paquete");
            return;
        }
        if(jComboBox1.getSelectedIndex()==1){
            TipoUsuario="D";
            TotalD++;
        }
        else if (jComboBox1.getSelectedIndex()==2){
            TipoUsuario="M";
            TotalM++;
        }
        else if (jComboBox1.getSelectedIndex()==3){
            TipoUsuario="E";
            TotalE++;
        }
        else if (jComboBox1.getSelectedIndex()==4){
            TipoUsuario="R";
            TotalR++;
        }
        
        if(jComboBox2.getSelectedIndex()==1){
            if(jComboBox1.getSelectedIndex()==1) CDP++;
            else if (jComboBox1.getSelectedIndex()==2)CMP++;
            else if (jComboBox1.getSelectedIndex()==3)CEP++;
            else if (jComboBox1.getSelectedIndex()==4)CRP++;
            TipoPaquete="P";
            String Ficha=TipoPaquete+"-"+TipoUsuario+"-"+NFicha;
            NFicha++;
            Fichas NuevaFicha=new Fichas(jTextField1.getText(),jTextField2.getText(),
                jComboBox1.getSelectedIndex(),jComboBox2.getSelectedIndex(),Ficha);
        //t = NuevaFicha;
            CantidadP++;
        
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        String info=("Ficha Creada"+"\nNombre: "+NuevaFicha.getNombre()+"\nCorreo: "+NuevaFicha.getCorreo()+"\nFicha: "+NuevaFicha.getFicha());
        JOptionPane.showMessageDialog(this, info);
        PrioridadP.enqueue(NuevaFicha, NuevaFicha.getTipoUsuario()-1);
        TotalP+="\n "+NuevaFicha.getFicha();
        AtendidosP+=1;
       
        
        }
        else if(jComboBox2.getSelectedIndex()==2){
            if(jComboBox1.getSelectedIndex()==1) CDNP++;
            else if (jComboBox1.getSelectedIndex()==2)CMNP++;
            else if (jComboBox1.getSelectedIndex()==3)CENP++;
            else if (jComboBox1.getSelectedIndex()==4)CRNP++;
            TipoPaquete="NP";
            String Ficha=TipoPaquete+"-"+TipoUsuario+"-"+NFicha2;
            NFicha2++;
            Fichas NuevaFicha=new Fichas(jTextField1.getText(),jTextField2.getText(),
                jComboBox1.getSelectedIndex(),jComboBox2.getSelectedIndex(),Ficha);
        //t = NuevaFicha;
        
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        String info=("Ficha Creada"+"\nNombre: "+NuevaFicha.getNombre()+"\nCorreo: "+NuevaFicha.getCorreo()+"\nFicha: "+NuevaFicha.getFicha());
        JOptionPane.showMessageDialog(this, info);
            
        PrioridadNP.enqueue(NuevaFicha, NuevaFicha.getTipoUsuario()-1);
        CantidadNP++;
        TotalNP+="\n "+NuevaFicha.getFicha();
        AtendidosNP+=1;
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void FieldEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldEActionPerformed

    private void FieldSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldSActionPerformed

    private void ButtonCantVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCantVentActionPerformed
        int cantVEntregas, cantVENoP, cantVSeguridad, cantVSNop;
        
        if(((FieldE.getText() == null || FieldE.getText().equals("")) || (FieldS.getText() == null || FieldS.getText().equals(""))) || ((FieldENoP.getText() == null || FieldENoP.getText().equals("")) || (FieldSNoP.getText() == null || FieldSNoP.getText().equals("")))) {
            JOptionPane.showMessageDialog(null,"Debe ingresar un numero en los espacios");
            return;
        }
        
        cantVEntregas = Integer.parseInt(FieldE.getText());
        cantVENoP = Integer.parseInt(FieldENoP.getText());
        cantVSeguridad = Integer.parseInt(FieldS.getText());
        cantVSNop = Integer.parseInt(FieldSNoP.getText());
        
        //crear ventanas en el quisco
        for(int i=0;i<cantVEntregas;i++) {
   
            String Dato[]=new String[3];
            Dato[0]= "Ventanilla "+cont1;
            Dato[1]="";
            Dato[2]="";
            ventanilla1.addRow(Dato);
            cont1++;
        }
        for(int i=0;i<cantVENoP;i++) {
            String Dato[]=new String[3];
            Dato[0]= "Ventanilla "+cont2;
            Dato[1]="";
            Dato[2]="";
            ventanilla2.addRow(Dato);
            cont2++;
        }
        for(int i=0;i<cantVSeguridad;i++) {
            String Dato[]=new String[3];
            Dato[0]= "Ventanilla "+cont3;
            Dato[1]="";
            Dato[2]="";
            ventanilla3.addRow(Dato);
            cont3++;
        }
        for(int i=0;i<cantVSNop;i++) {
            String Dato[]=new String[3];
            Dato[0]= "Ventanilla "+cont4;
            Dato[1]="";
            Dato[2]="";
            ventanilla4.addRow(Dato);
            cont4++;
        }

    }//GEN-LAST:event_ButtonCantVentActionPerformed

    private void FieldENoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldENoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldENoPActionPerformed

    private void Atender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atender1ActionPerformed
        int Fila=jTable1.getSelectedRow();
        if (Fila==-1) JOptionPane.showMessageDialog(null, "Seleccione la ventanilla donde desea ser atendido");
        else if(Fila>=0){
            Ficha=(Fichas) PrioridadP.dequeue();              
        int reglon = jTable1.getSelectedRow();
        ventanilla1.setValueAt("Atendiendo", reglon, 1);
        ventanilla1.setValueAt(Ficha.getFicha(), reglon, 2);
        String TUsuario = "";
        int infTable = (int) Ficha.getTipoUsuario();
            switch (infTable) {
                case 1:
                    TUsuario = "Discapacitado";
                    break;
                case 2:
                    TUsuario = "Adulto Mayor";
                    break;
                case 3:
                    TUsuario = "Embarazada";
                    break;
                case 4:
                    TUsuario = "Regular";
                    break;
                default:
                    break;
            }
        ventanilla1.setValueAt(TUsuario, reglon, 3);
        CantidadP--;
        }
    }//GEN-LAST:event_Atender1ActionPerformed

    private void Atender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atender2ActionPerformed
        int Fila2=jTable1.getSelectedRow();
        if (Fila2==-1) JOptionPane.showMessageDialog(null, "Seleccione la ventanilla donde desea ser atendido");
        else if(Fila2>=0){
        Ficha=(Fichas) PrioridadNP.dequeue();
        
        int reglon = jTable2.getSelectedRow();
        ventanilla2.setValueAt("Atendiendo", reglon, 1);
        ventanilla2.setValueAt(Ficha.getFicha(), reglon, 2);
        String TUsuario = "";
        int infTable = (int) Ficha.getTipoUsuario();
            switch (infTable) {
                case 1:
                    TUsuario = "Discapacitado";
                    break;
                case 2:
                    TUsuario = "Adulto Mayor";
                    break;
                case 3:
                    TUsuario = "Embarazada";
                    break;
                case 4:
                    TUsuario = "Regular";
                    break;
                default:
                    break;
            }
        ventanilla2.setValueAt(TUsuario, reglon, 3);
        CantidadNP--;
        }
    }//GEN-LAST:event_Atender2ActionPerformed

    private void Liberar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Liberar2ActionPerformed
        int Fila3=jTable2.getSelectedRow();
        if (Fila3==-1) JOptionPane.showMessageDialog(null, "Seleccione la ventanilla a liberar");
        else if(Fila3>=0){
        int renglon = jTable2.getSelectedRow();
        int TUsuario = 0;
        String infTable = (String) jTable2.getValueAt(Fila3, 3);
        if( null != infTable) switch (infTable) {
                case "Discapacitado":
                    TUsuario = 1;
                    break;
                case "Adulto Mayor":
                    TUsuario = 2;
                    break;
                case "Embarazada":
                    TUsuario = 3;
                    break;
                case "Regular":
                    TUsuario = 4;
                    break;
                default:
                    break;
            }
        Fichas FichaS = new Fichas(TUsuario,(String) jTable2.getValueAt(Fila3, 2));
        SeguridadNP.enqueue(FichaS, TUsuario - 1);
        ventanilla2.setValueAt("Libre", renglon, 1);
        ventanilla2.setValueAt("-", renglon, 2);
        ventanilla2.setValueAt("-", renglon, 3);
        
        }
    }//GEN-LAST:event_Liberar2ActionPerformed

    private void Liberar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Liberar1ActionPerformed
        int Fila4=jTable1.getSelectedRow();
        if (Fila4==-1) JOptionPane.showMessageDialog(null, "Seleccione la ventanilla a liberar");
        else if(Fila4>=0){
        int renglon = jTable1.getSelectedRow();
        int TUsuario = 0;
        String infTable = (String) jTable1.getValueAt(Fila4, 3);
        if( null != infTable) switch (infTable) {
                case "Discapacitado":
                    TUsuario = 1;
                    break;
                case "Adulto Mayor":
                    TUsuario = 2;
                    break;
                case "Embarazada":
                    TUsuario = 3;
                    break;
                case "Regular":
                    TUsuario = 4;
                    break;
                default:
                    break;
            }
        Fichas FichaS = new Fichas(TUsuario,(String) jTable1.getValueAt(Fila4, 2));
        Seguridad.enqueue(FichaS, TUsuario - 1);
        ventanilla1.setValueAt("Libre", renglon, 1);
        ventanilla1.setValueAt("-", renglon, 2);
        ventanilla1.setValueAt("-", renglon, 3);
        
        }
        
    }//GEN-LAST:event_Liberar1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String EstadoP;
        EstadoP = String.valueOf(CantidadP);
        String EstadoNP;
        EstadoNP = String.valueOf(CantidadNP);
        //PrioridadP.First();
        
        String Estados="Cantidad en Perecederos: "+EstadoP+"\n"+"\nCantidad en No Perecederos: "+EstadoNP+"\n"+
                "\nFichas de clientes en Perecederos: "+TotalP+"\nFichas de clientes en No Perecederos: "+TotalNP;
        JOptionPane.showMessageDialog(this, Estados);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Estadist="Fichas dispensadas en Perecederos:\t  "+AtendidosP+"\nFichas dispensadas en "
                + "No Perecederos: "+AtendidosNP+"\n"+"\nUsuarios Regulares atendidos:"+TotalR+"\nAdultos mayores atendidos:"+
                TotalM+"\nUsuarios Discapacitados atendidos:"+TotalD+"\nMujeres embarazadas atendidas:"+TotalE+"\n"+
                "\nUsuarios atendidos en Perecederos:"+"\nUsuarios Discapacitados atendidos: "+CDP+
                "\n Adultos Mayores atendidos: "+CMP+"\nMujeres Embarazadas atendidas: "+CEP+"\nUsuarios Regulares atendidos: "+CRP+
                "\n"+"\nUsuarios atendidos en No Perecederos:"+"\nUsuarios Discapacitados atendidos: "+CDNP+
                "\n Adultos Mayores atendidos: "+CMNP+"\nMujeres Embarazadas atendidas: "+CENP+"\nUsuarios Regulares atendidos: "+CRNP;
        
        JOptionPane.showMessageDialog(this, Estadist);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atender1;
    private javax.swing.JButton Atender2;
    private javax.swing.JButton ButtonCantVent;
    private javax.swing.JTextField FieldE;
    private javax.swing.JTextField FieldENoP;
    private javax.swing.JTextField FieldS;
    private javax.swing.JTextField FieldSNoP;
    private javax.swing.JButton Liberar1;
    private javax.swing.JButton Liberar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
